[package]
name = "cmt-concurrent"
version = "0.1.0"
edition = "2021"

[dependencies]
cmt-core = { path = "../cmt-core" }
rayon = "1.8.1"
parking_lot = { version = "0.12.1", features = ["serde"] }
sha2 = "0.10.9"