[package]
name = "cmt-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
cmt-core = { path = "../cmt-core" }
cmt-concurrent = { path = "../cmt-concurrent" }
criterion = "0.5"
rayon = "1.8.1"

[[bench]]
name = "cmt_benches"
harness = false